### PR TITLE
Add Presidio PII Redaction Filter

### PR DESCRIPTION
**Pull request by justinh-rahb**
## Introducing the Presidio PII Redaction Filter

This PR presents a robust enhancement to data privacy with the **Presidio PII Redaction Filter**, now implemented in: `presidio_filter_pipeline.py`. This filter is designed to streamline the identification and redaction of sensitive Personally Identifiable Information (PII) from text data.

download

**PII Redaction Features:**

- The filter automatically detects a wide variety of PII entities, ensuring compliance with data protection regulations.
- Supported entities include:
  - `PERSON`
  - `EMAIL_ADDRESS`
  - `PHONE_NUMBER`
  - `US_SSN`
  - `CREDIT_CARD`
  - `IP_ADDRESS`
  - `US_PASSPORT`
  - `LOCATION`
  - `DATE_TIME`
  - `NRP` (National Reference Point)
  - `MEDICAL_LICENSE`
  - `URL`

**Pipeline Configuration Options:**

- **Pipelines:** Specifies which underlying machine learning models to leverage for the PII detection, with a customizable list: 
  - Example:
  ```
  cohere.c4ai-aya-23,cohere.command-r-plus,google_gen_ai.gemini-1.5-flash-latest
  ```
  
- **Priority:** Set the processing priority for this filter (default is 0), allowing users to manage the order of execution in multi-pipeline configurations.

- **Enable for Admins:** The filter can be toggled on/off specifically for admin use, providing flexibility in access control.

- **Language Support:** Adjust the language setting (default is English) to enhance PII detection accuracy in different linguistic contexts.

---

This enhancement to the Pipelines framework provides a comprehensive solution for PII handling, enabling organizations to protect sensitive information efficiently while maintaining flexibility in their data processing workflows.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Screenshot 2024-07-23 at 11 04 03 PM

**Comment by robomotic** [comment]
How can we get the filter to run BEFORE a web search so that we don't leak PII on the web?
This happens when I search for a private email:

image

Response:

image

I am not sure if this is a limitation or edge case of the actual framework, maybe the async nature of the filter means that by the time the output is process the websearch is already triggered?

**Comment by robomotic** [comment]
Also @justinh-rahb seems like the Valves are not valid anymore in recent versions of the UI:

image

**Comment by tjbck** [comment]
@robomotic Please refrain from tagging random contributors. 

This issue might be addressed with the latest Open WebUI dev branch, and No, Pipeline Valves never supported `UserValves`.

**Pull request merged**
