### PR TITLE
Google Translate Integration

### PR DESCRIPTION
**Pull request by OriginalSimon**
I propose to include the function of automatic translation of user and assistant messages using Google Translate in our project. The function does not require the use of API key and uses publicly available API points.

Переводчик Гугл для Open WebUI
Пишіть код на C++ та C та Python - привіт світу

### CODE REVIEW

**Comment by justinh-rahb** [comment]
LGTM, works as advertised!

**Comment by justinh-rahb** [comment]
While it's unfortunate that Pipelines currently lack the `UserValves` functionality present in WebUI's Functions, it would be highly beneficial to have it for this application. However, it's worth noting that the translation filter could be readily ported to Functions. This approach would enable per-user configuration and eliminate the need for a separate server. 🤌

**Comment by justinh-rahb** [comment]
Hmmm turns out, very easy to port:
https://openwebui.com/f/justinrahb/google_translate_filter

**Comment by euroblaze** [comment]
> I propose to include the function of automatic translation of user and assistant messages using Google Translate in our project. The function does not require the use of API key and uses publicly available API points.

Similarly DeepL.com is known to be a superior translation service.

**Comment by tjbck** [comment]
LGTM, Thanks!

**Pull request merged**
