### PR TITLE
Ollama Dynamic Vision Pipeline

### PR DESCRIPTION
**Pull request by atgehrhardt**
This allows you so select an Ollama model to override with another Ollama image model. If an image is attached, it will send the image over to the override model and that model will return it's description and the initial model will take back over.

This isn't perfect, but allows you to take any text model, check the vision option, and have it process images without breaking the UI by leaning on another model.

This is JUST A STARTING POINT.

There is a LOT more we can do to make this more robust, but it serves as a good starting point.

### CODE REVIEW

**Comment by tjbck** [comment]
wow-rogan

LET'S GOOOOOOOOOOOOOO!!!

FYI, most of the filters will also be compatible with https://github.com/open-webui/open-webui/issues/3247.

**Comment by Hugobox** [comment]
Hi @atgehrhardt !

Could this pipeline currently work with our setup? We have disabled Ollama API (in admin - models), but we have enabled llama-3-70b (text-only) and also InternVL-Chat-V1-5 (text and images) (admin - connections). I tried installing this pipeline, then configured it as follows: 
Vision Model: InternVL-Chat-V1-5
Ollama Base Url: (tried both the url for Llama and InternVL, should it be the URL for the text-only model or the URL for the vision model?)
Model to override: llama-3-70b
Is Ollama required for this pipeline to work or should it also work with openAI compatible APIs through Connections?

**Comment by atgehrhardt** [comment]
@Hugobox currently this is outdated and only works with Ollama given the url config but could be easily adjusted to use an OpenAI compatible endpoint.

**Comment by atgehrhardt** [comment]
I believe you'd just need to change the url in line 43 to reflect the OpenAI compat endpoint

**Comment by Hugobox** [comment]
@atgehrhardt Ok thanks! When you say its outdated, do you mean there's a newer version available? I've cloned the pipelines repo and modified the line 43, but I think the pipeline is not even executed in my case, In the logs I get a lot of embedding errors, so I think the RAG tries to parse the image as if it was a text file and fails.

**Comment by Hugobox** [comment]
I found and tried the semantic model router  https://openwebui.com/f/atgehrhardt/semantic_model_router/
And this time I can see meaningful logs, it still fails, but at least I think its because its missing the API key.

**Comment by Hugobox** [comment]
Got the semantic model router working by adding the API key in the header of the http post request, still getting RAG errors, but really glad to have a working solution! Thanks!

**Comment by Hugobox** [comment]
I now simplified the router function code, it works but not always, turns out I didn't need API keys. If the uploaded image is in the first message of the conversation, it always works, if its in the 3rd, then the reply becomes empty, but in both cases if passes through the function and detects that an image has been uploaded. Is there a way to debug what happens between the inlet and the outlet?

`
from typing import List, Union, Generator, Iterator, Optional
from pydantic import BaseModel

class Filter:
    class Valves(BaseModel):
        pass
    def __init__(self):
        self.file_handler = True
        pass

    def inlet(self, body: dict, user: Optional[dict] = None) -> dict:
        def has_image(messages):
            for message in messages:
                if "content" in message:
                    content = message["content"]
                    if isinstance(content, list):
                        for item in content:
                            if item["type"] == "image_url":
                                return True
                    elif "image_url" in content:
                        return True
            return False

        result = has_image(body["messages"])
        if result:
            if body["model"] == "casperhansen/llama-3-70b-instruct-awq":
                body["model"] = (
                    "/root/.cache/huggingface/hub/models--OpenGVLab--InternVL-Chat-V1-5-AWQ/snapshots/5ce4e49fe4e5d960b62a619b268113e40943c57f"
                )
        print(f"inlet:{__name__}")
        print(f"inlet:body:{body}")
        print(f"inlet:user:{user}")
        return body

    def outlet(self, body: dict, user: Optional[dict] = None) -> dict:
        print(f"outlet:{__name__}")
        print(f"outlet:body:{body}")
        print(f"outlet:user:{user}")`

**Pull request merged**
