### PR TITLE
Add minimum docker build

### PR DESCRIPTION
**Pull request by chemwolf6922**
Thanks jtha for their experiments. 
## Why
* This PR means to reduce the docker image size. Please checkout discussion here https://github.com/open-webui/pipelines/discussions/282
## Changes
* Add a minimum build type that removes all unused python packages. 
* Move document picture under docs.
## Tests
* Tested with the azure open ai pipeline. 
## TODO
* Please help test other pipelines.
* Please help review the changes to the github ci pipeline.

### CODE REVIEW

**Comment by tjbck** [comment]
Quick q: will this PR add an additional tag like `:min` or will this override the existing `:main`

**Comment by chemwolf6922** [comment]
@tjbck I aim to add a new tag to avoid regression on any user that may have used the unused packages in their pipelines w/o declaring those. 
I have not tested the Github ci pipeline for building and tagging the image though.

**Comment by chemwolf6922** [comment]
@tjbck Please feel free to edit the tag or variable name if min is preferred.

**Comment by tjbck** [comment]
Thanks for the response, LGTM! We should be good to merge after we rebase this PR!

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by jtha** [comment]
Thank you @chemwolf6922 for actually making the PR and now we have an official minimum image! Apologies for the laziness on my part.

**Pull request merged**
