### PR TITLE
add a LangGraph example via FastAPI 20240715

### PR DESCRIPTION
**Pull request by dukai289**
To use LangGraph or LangChain, we build a FastAPI web service.Then we can call this service in openwebui-pipelines

### CODE REVIEW

**Comment by dukai289** [comment]
I appreciate your work, pipelines truly give us the ability to customize any LLM application.
And I hope that in the future I can contribute ideas and code to create better communities and applications.

**Comment by PlebeiusGaragicus** [comment]
This is EXACTLY what I was working to build!!!  This is so powerful!

Bless you!!

**Comment by PlebeiusGaragicus** [comment]
Wait - why closed and not merged?

I am currently working towards exactly this use-case.

**Comment by justinh-rahb** [comment]
Pipelines are to be self-contained in a single file.

**Comment by PlebeiusGaragicus** [comment]
Got it - I was going to fork the pipeline repo and bring in all my agent code, but I think I won't now after doing more digging.  I'll continue to keep my pipeline module very simple and run my LangGraph agent as a FastAPI endpoint that the pipeline will call.

**Pull request closed without merging**
