### PR TITLE
feat: Add MLX Manifold Pipeline

### PR DESCRIPTION
**Pull request by justinh-rahb**
## Introducing the MLX Manifold Pipeline (v2.0)

This PR introduces a significant enhancement to the MLX pipeline with the **MLX Manifold Pipeline**, located in a new file: `mlx_manifold_pipeline.py`. This new pipeline offers major improvements:

**Manifold Support:**

- The pipeline automatically detects and lists all available HF models with a defined filter keyword. 
- This removes the need for manual model configuration and makes model selection easier.

**Dynamic Model Loading:**

- The pipeline dynamically loads and uses the selected MLX model when run.
- This eliminates static model definitions and allows for more flexible model experimentation and deployment.

**Version 2.0:**

- This update is a major version bump (v2.0) due to the substantial changes introduced.
- The existing MLX pipeline remains untouched to ensure backward compatibility. 

**Migration:**

- Users can switch to `mlx_manifold_pipeline.py` to use the new Manifold Pipeline, but should not run both on the same MLX backend server.

**Testing:**

- The MLX Manifold Pipeline needs more thorough testing before merging, help wanted!

### Using the Valves:

- **MLX Model Filter:** Filter available models to show only ones matching the filter keyword.
- **MLX Default Model:** Set a default model to be automatically loaded.
  - If not found locally, it will be downloaded (similar to Ollama's pull feature).
- **MLX Stop:** Define stop words that will trigger the inference to end.
- **MLX Chat Template:** Specify a custom chat template to use.
- **MLX Use Default Chat Template:** True/False (default False)
- **HuggingFace Token:** Provide your token for accessing private models.

**Note:** Setting an environment variable for your HuggingFace cache can point to an alternate model location, bypassing the need for the MLX Model Pattern filter.

---

This enhancement makes the MLX pipeline more usable and flexible, allowing users to better utilize their MLX models.

### CODE REVIEW

**Comment by tjbck** [comment]
Can't wait to try this 🤩 Thanks!

**Comment by justinh-rahb** [comment]
Forgot the teasers 😬

Screenshot 2024-06-30 at 1 40 29 AM

Screenshot 2024-06-30 at 1 36 43 AM

https://github.com/open-webui/pipelines/assets/52832301/bf98af9e-1605-4261-82c7-8ee4e71807d1

**Comment by justinh-rahb** [comment]
### TODO for MLX Manifold Pipeline PR:

- **Remove `MLX_SUBPROCESS=False` option:** This is essential for the dynamic model loading. 
- **Document containerization limitations:** Running Pipelines on bare metal is required due to the removal of the subprocess option.
- **Consider a helper script:** Explore creating a script that simplifies installation and running of the MLX Pipelines server on macOS.
- **Investigate `mlx_lm` direct usage (v2.0 ONLY):**  Since `MLX_SUBPROCESS=False` is being removed in v2.0, directly using the `mlx_lm` library instead of `mlx_lm.serve` might be possible and more efficient. This needs further investigation.

**Comment by tjbck** [comment]
Let's goooooo 🚀

**Pull request merged**
